// Generates the SYNTHETIC demo files from the evidence bundle's own site
// definitions (forward-strand alleles, GRCh37 positions). No real person's data.
import { readFileSync, writeFileSync } from "node:fs";
import type { EvidenceBundle, VariantSite } from "../src/core/types";

const b: EvidenceBundle = JSON.parse(readFileSync("src/evidence/bundle.json", "utf8"));

/** The allele a demo "copy" refers to: the ClinVar allele if there is one, else dbSNP's main alternate allele. */
function altFor(s: VariantSite): string {
  return b.clinvar.find((r) => r.rsid === s.rsid && r.stars > 0)?.altAllele ?? s.mainAlt;
}
function call(s: VariantSite, copies: number): string[] {
  const alt = altFor(s);
  const ref = alt === s.ref ? s.alts[0] : s.ref;
  if (s.kind === "deletion" || s.kind === "insertion") {
    const altCode = s.kind === "deletion" ? "D" : "I", refCode = s.kind === "deletion" ? "I" : "D";
    return [copies >= 1 ? altCode : refCode, copies === 2 ? altCode : refCode];
  }
  return [copies >= 1 ? alt : ref, copies === 2 ? alt : ref].sort();
}

// copies of altFor(site); "skip" = not on the chip; "nc" = no-call
type Spec = Record<string, number | "skip" | "nc">;
const spec23: Spec = {
  rs1800562: 1, rs1799945: 1, rs6025: 0, rs1799963: 0, rs113993960: 0, rs334: 0, rs76763715: 0, rs80357906: "skip", rs80359550: "nc",
  rs7903146: 1, rs1801282: 0, rs429358: 1, rs7412: 0, rs4988235: 0, rs1801133: 2, rs9939609: 1, rs671: 0, rs1229984: 0,
  rs2282679: 1, rs2472297: 1, rs762551: 1, rs1815739: 1,
};
const specAnc: Spec = {
  rs1800562: 2, rs1799945: 0, rs6025: 1, rs1799963: 0, rs113993960: "skip", rs334: 0, rs76763715: "skip", rs80357906: "skip", rs80359550: "skip",
  rs7903146: 2, rs1801282: 1, rs429358: 0, rs7412: 1, rs4988235: 2, rs1801133: 0, rs9939609: 0, rs671: 1, rs1229984: 1,
  rs2282679: 0, rs2472297: 0, rs762551: "nc", rs1815739: 2,
};
const FILLER = 3000;
const BASES = ["A", "C", "G", "T"];
const rng = (() => { let x = 42; return () => ((x = (x * 1103515245 + 12345) % 2 ** 31) / 2 ** 31); })();
const chromNum = (c: string) => ({ X: "23", Y: "24", MT: "26" } as Record<string, string>)[c] ?? c;

function rows(spec: Spec) {
  return b.sites.filter((s) => spec[s.rsid] !== "skip" && spec[s.rsid] !== undefined).map((s) => {
    const v = spec[s.rsid];
    return { rsid: s.rsid, chrom: s.chrom, pos: s.pos37 ?? 0, alleles: v === "nc" ? null : call(s, v as number) };
  });
}
function filler(i: number) {
  const a = BASES[Math.floor(rng() * 4)], c = BASES[Math.floor(rng() * 4)];
  return { rsid: `rs${2_100_000_000 + i}`, chrom: String(1 + (i % 22)), pos: 1_000_000 + i * 97, alleles: rng() < 0.01 ? null : [a, c].sort() };
}

const all23 = [...rows(spec23), ...Array.from({ length: FILLER }, (_, i) => filler(i))];
writeFileSync("src/demo/synthetic-23andme.txt", [
  "# SYNTHETIC DEMO FILE: generated by scripts/make-demo.ts. Not a real person's genotype.",
  "# This data file generated by 23andMe at: Thu Jan 01 00:00:00 2026",
  "# More information on reference human assembly build 37 (a.k.a. Annotation Release 104):",
  "# rsid\tchromosome\tposition\tgenotype",
  ...all23.map((r) => `${r.rsid}\t${r.chrom}\t${r.pos}\t${r.alleles ? r.alleles.join("") : "--"}`),
].join("\n") + "\n");

const allAnc = [...rows(specAnc), ...Array.from({ length: FILLER }, (_, i) => filler(i + FILLER))];
writeFileSync("src/demo/synthetic-ancestrydna.txt", [
  "#AncestryDNA raw data download",
  "#SYNTHETIC DEMO FILE: generated by scripts/make-demo.ts. Not a real person's genotype.",
  "#Genetic data is provided below as five TAB delimited columns. Columns two and three contain the chromosome and basepair position of the SNP using human reference build 37.1 coordinates.",
  "rsid\tchromosome\tposition\tallele1\tallele2",
  ...allAnc.map((r) => `${r.rsid}\t${chromNum(r.chrom)}\t${r.pos}\t${r.alleles ? r.alleles.join("\t") : "0\t0"}`),
].join("\r\n") + "\r\n");
console.log(`demo files: ${all23.length} and ${allAnc.length} rows`);
